### PR TITLE
Step 4: Hooks

### PR DESCRIPTION
**Pull request by bidoubiwa**
In this PR

### On launch of server: 
Create hooks by surcharging lifecycles functions of collections that are indexed in MeiliSearch

### On the plugin page
- A reload server button when hooks must be updated
- A hooks column that mentioned you should reload or if hooks are active
- An update button if you want to update manually your data to MeiliSearch
 
fixes: #79 -> automatic hooks
fixes: #18 -> Hooks
fixes: #16 -> Step 4
fixes: #58 -> If collection is in draft mode it is still added to MeiliSearch if the users ask for it
fixes: #84 -> server reload brings back to plugin page

### CODE REVIEW

**Comment by MANTENN** [comment]
works for 100 records only. each time a record gets added only 100 are in the system.

**Comment by bidoubiwa** [comment]
> works for 100 records only. each time a record gets added only 100 are in the system.

Does the hook only capture 100 records? 

Thanks a lot for reporting a bug. I should try the plugin with a bigger dataset

**Comment by MANTENN** [comment]
> > works for 100 records only. each time a record gets added only 100 are in the system.
> 
> Does the hook only capture 100 records?
> 
> Thanks a lot @MANTENN for reporting a bug. I should try the plugin with a bigger dataset

Yup, I implemented a que on my own using `bee-queue` npm module so the nodejs is free to handle requests.

**Comment by MANTENN** [comment]
@bidoubiwa here's my code for the queue. It's a rough implementation.

https://github.com/MANTENN/strapi-plugin-meilisearch/tree/step_4

**Comment by bidoubiwa** [comment]
Hey @MANTENN!
Your repo is really hard to read with the linting and the merging.
Could you: 
1. Create a branch that starts from step_4
2. Add your code
3. Create PR that points to `step_4` (line on the following example, it is not pointing to master)

Screenshot 2021-03-28 at 13 42 51

Could you also if it is not to much, start the conversation in an issue as this PR will be flooded with change requests monday haha

**Comment by MANTENN** [comment]
> Hey @MANTENN!
> Your repo is really hard to read with the linting and the merging.
> 
> Could you:
> 
> 1. Create a branch that starts from step_4
> 2. Add your code
> 3. Create PR that points to `step_4` (like on the following example, it is not pointing to master)
> 
> Screenshot 2021-03-28 at 13 42 51
> 
> Could you also if it is not to much, start the conversation in an issue as this PR will be flooded with change requests monday haha

Yes, I would have to do it on Tuesday. Need to file taxes on Monday.

**Comment by bidoubiwa** [comment]
@MANTENN  no problem! I started the issue #88 :)

**Comment by bidoubiwa** [comment]
Ah yes, related to the readme that I changed. They used the assets that will be changed in this pr #90. I will remove them!

**Review by curquiza — APPROVED** [review]
Awesome!!

**Comment by bidoubiwa** [comment]
bors merge

**Pull request merged**
