### PR TITLE
Update version for the next release (v0.6.3)

### PR DESCRIPTION
**Pull request by bidoubiwa**
As per [the contributing rules](https://github.com/meilisearch/strapi-plugin-meilisearch/blob/main/CONTRIBUTING.md#how-to-publish-the-release)

### CODE REVIEW

**Comment by dzcpy** [comment]
May I ask when do you think it will be available :) ? We are working on a project which depends on async transformEntry, not meant to be pushy but it's nice to know when we can use it instead of installing directly from github. Many thanks!

**Review by nicolasvienot — APPROVED** [review]

**Comment by bidoubiwa** [comment]
@dzcpy this week or next week :) I want to release the `transformEntry` async in the same release

**Comment by brunoocasali** [comment]
@bidoubiwa what do you think about sending the release notes in the description of this kind of PR? (I didn't see much value in the current way we've been doing it 😊)

**Comment by bidoubiwa** [comment]
@brunoocasali I'm not sure I see what you mean. Do you mean the content of this: https://github.com/meilisearch/strapi-plugin-meilisearch/releases/tag/untagged-7454dc5d18ac0c01c348 in the body of this PR?

**Comment by bidoubiwa** [comment]
bors merge

**Pull request merged**
