### PR TITLE
Add possibility to configure via plugin config

### PR DESCRIPTION
**Pull request by sargreal**
If plugin config is used, adding or changing the credentials from the admin interface is disabled and the api key is masked.

I am not sure if the approach is the best, and I also don't know if configuration from both sides should still be possible.

Not sure how to test this, since the server needs to be restarted when the plugin config changes. So it would maybe require an extra test environment?

Implements #41

### CODE REVIEW

**Comment by bidoubiwa** [comment]
Hello @sargreal

Thanks so much for this PR. This is really needed. I will review it ASAP :) 

Just FYI, we encourage everyone to make a PR from a **new branch** created in their fork-repository instead of doing it from their own `master`, it is a good practice! For example, if your PR was not merged you would have had a broken `master` branch compared to ours.
See here our [contribution guidelines](https://github.com/meilisearch/meilisearch-js/blob/master/CONTRIBUTING.md#how-to-contribute).
I'm saying this for the next time, let's keep it like this for this PR. 😉

**Comment by bidoubiwa** [comment]
Hey sargeal, I made some changes to your code as they are to big to make you do them step by step in a review. Unfortunately I can't make a PR that points on your PR. Could you give me write access on your fork just the time I make the PR that's points on your PR?

**Comment by sargreal** [comment]
> Hey sargeal, I made some changes to your code as they are to big to make you do them step by step in a review. Unfortunately I can't make a PR that points on your PR. Could you give me write access on your fork just the time I make the PR that's points on your PR?

Sure, but shouldn't that already be handled by the "Allow edits by maintainers" feature? 🤔

**Comment by bidoubiwa** [comment]
Yes, but I dont like the fact that I overwrite your code without you reviewing what I add

**Review by bidoubiwa — CHANGES_REQUESTED** [review]
See https://github.com/sargreal/strapi-plugin-meilisearch/pull/1

**Review by bidoubiwa — APPROVED** [review]
LGTM 🔥

**Comment by bidoubiwa** [comment]
bors merge

**Pull request merged**
