### PR TITLE
Workaround for locales

### PR DESCRIPTION
**Pull request by fhenri42**
# Pull Request

## What does this PR do?
Fixes 263
https://github.com/meilisearch/strapi-plugin-meilisearch/issues/263

## PR checklist
Please check if your PR fulfills the following requirements:
- [X] Does this PR fix an existing issue?
- [X] Have you read the contributing guidelines?
- [X] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by bidoubiwa** [comment]
Hello @fhenri42 how does it look like when added to Meilisearch?

**Comment by bidoubiwa** [comment]
Hey @fhenri42 it could become a setting yes :) Let's see what your investigation brings up before going into that direction

**Comment by fhenri42** [comment]
Hey @bidoubiwa I remove the Internationalization in a new app and did not have any issues

**Comment by Hedg0305** [comment]
Any idea of when this MR will be approved?

**Comment by bidoubiwa** [comment]
Hey @Hedg0305 

I think i'm going to move it to a setting to avoid unexpected behaviors to users not wanting this option. I'll keep you updated as soon as I come back on this pr :)

**Comment by bidoubiwa** [comment]
Hey @fhenri42. I tried your suggested changes without having the `@strapi/plugin-i18n` plugin and it fails. 

I'm trying to find if I can check its presence and depending on it add the `local: 'all'` to the request

**Comment by bidoubiwa** [comment]
I found a work-around, since you are doing your changes on a `main` branch I can unfortunately not commit to it. I'm merging this PR in another branch to update it :) 

Thanks for contributing !

**Comment by bidoubiwa** [comment]
_This message is sent automatically_

Thank you for contributing to Meilisearch. If you are participating in [Hacktoberfest](https://blog.meilisearch.com/contribute-hacktoberfest-2022/), and you would like to receive some gift from Meilisearch too, please complete [this form](https://meilisearch.typeform.com/to/idt5qugY).

**Pull request merged**
