### PR TITLE
Create a custom _meilisearch_id field instead of overwriting the existing id

### LINKED ISSUE #609: Create a custom `_meilisearch_id` field instead of overwriting the existing `id` field.
See #608 

Currently, before an entry is indexed into Meilisearch, the plugin pre-prend its `id` with the collection name.
For example:

```
Restaurant {
id: 1,
name: "Pizza Freak" 
}
```

In Strapi becomes:

```
Restaurant {
id: "restaurant-1",
name: "Pizza Freak" 
}
```

In Meilisearch.

The user is not aware of this change and it might lead to confusion as it is not well documented.

To solve this issue, instead of overwriting the `id` field, the plugin should create a new field named `_meilisearch_id` containing the transformed value of the id:

```
Restaurant {
id: 1,
_meilisearch_id: "restaurant-1",
name: "Pizza Freak" 
}
```

## TODO
- Change `id` to `_meilisearch_id` here
https://github.com/meilisearch/strapi-plugin-meilisearch/blob/354db6c888648412c339fb592ba836f726daea59/server/services/meilisearch/adapter.js#L37-L45
- In every occurrence of `client.index(indexUid).addDocuments(documents)` the primary key should be specifically provided. [See doc](https://docs.meilisearch.com/reference/api/documents.html#add-or-replace-documents)
```js
client.index(indexUid).addDocuments(documents, { primaryKey: "_meilisearch_id" })
```
- add tests

### PR DESCRIPTION
**Pull request by Pablo-Aldana**
Documents ID are not overwritten now with this change, when indexing while keeping it possible to merge two collections into one index by adding a new ID _meilisearch_id it which would be the primaryKey for the indexes.

# Pull Request

## Related issue
Fixes #609 #608 

## What does this PR do?
- it creates a new internal id for the indexes: _meilisearch_id
- set primaryKey for the indexes as _meilisearch_id

## PR checklist
Please check if your PR fulfills the following requirements:
- [X ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [X ] Have you read the contributing guidelines?
- [ X] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by bidoubiwa** [comment]
Thanks so much for this PR 🙏

Could you also add the primary key on the `updateDocuments` method in `connector.js` ?

**Comment by Pablo-Aldana** [comment]
Wow! well spotted!!! already done :)

**Comment by bidoubiwa** [comment]
Hey @Pablo-Aldana, my bad I was not very present yesterday. I took a deeper look into your PR, could you also update the example in this file:  `resources/entries-query/populate.js` ?

**Comment by Pablo-Aldana** [comment]
> Hey @Pablo-Aldana, my bad I was not very present yesterday. I took a deeper look into your PR, could you also update the example in this file: `resources/entries-query/populate.js` ?

Hi @bidoubiwa !  I've been having a look and I'm not so sure what needs to be updated. the code on populate.js is as following
```
module.exports = {
  meilisearch: {
    config: {
      restaurant: {
        entriesQuery: {
          populate: ['repeatableComponent.categories', 'categories'],
        },
      },
    },
  },
}
```

from my little understanding, it should not affect the primaryKey on the query population isn't it?  at least I have done different tests and I can populate the information with the example in the resource without issues. 

Would you mind provide more details?

Thanks a lot!

**Comment by bidoubiwa** [comment]
Hey @Pablo-Aldana 

I'm merging your PR into another branch :) I'll be fixing the conflict and make the change in the `populate.js` file

**Pull request merged**
