### PR TITLE
Add yarn build step to the readme

### PR DESCRIPTION
**Pull request by LtdJorge**
Hi! Either I missed something or you forgot to put a "yarn build" step on the readme, so I added one. Let me know if I'm wrong and it should be done other way.

### CODE REVIEW

**Comment by LtdJorge** [comment]
Now that I think of it, this PR violates some of the contributing guidelines, but it's just a 5 lines addition to the readme, so I didn't even think about it.

**Comment by bidoubiwa** [comment]
Hey @LtdJorge 
Thanks so much for contributing so soon to this project! This step is missing yes, I forget that the build is not done automatically when running `yarn develop`. 

I also made some correction on the [README.md](https://github.com/meilisearch/strapi-plugin-meilisearch/blob/6babef3b6d7c72ed34e4387b1bb14a188ffdf7ab/README.md) in the other open PR #77 (nothing to do with your PR but just saying since you are looking at it haha)

**Comment by bidoubiwa** [comment]
> Now that I think of it, this PR violates some of the contributing guidelines, but it's just a 5 lines addition to the readme, so I didn't even think about it. 

which ones?

**Review by bidoubiwa — APPROVED** [review]

**Comment by bidoubiwa** [comment]
bors merge

**Comment by LtdJorge** [comment]
I didn't open an issue, for example. And yes, I saw that you are editing the readme too. I'm using MeiliSearch for a project and need Strapi interoperability, so I'm using the plugin even if it's early. One thing I noticed is that MS doesn't let you facet fields inside object fields, or am I wrong? I'm in the process of adding an object flattener to the output of this plugin (just for myself, unless you think it's useful for the main project), so that you can transform "field1":{"field2":string, "field3":string} into "field1:field2":string, "field1:field3":string.

**Comment by bidoubiwa** [comment]
> I didn't open an issue,
Ah yes, not needed in such cases.

>  One thing I noticed is that MS doesn't let you facet fields inside object fields

Yes exactly 

> I'm in the process of adding an object flattener to the output of this plugin (just for myself, unless you think it's useful for the main project),

If you are creating a tool for it, I would be very interested to see it. We could potentially add it to `meilisearch-js` as a helper function. 

Out of curiosity, do you need the flattener because of relationships in Strapi?

**Comment by LtdJorge** [comment]
> If you are creating a tool for it, I would be very interested to see it. We could potentially add it to `meilisearch-js` as a helper function.

Ok, I had thought about adding it to this plugin as a checkbox in the plugin's admin route. I'm just thinking of using [flattie](https://github.com/lukeed/flattie). Any recommendation on how to start? Should I directly do it on top of `meilisearch-js`, this plugin or MS itself? 

> Out of curiosity, do you need the flattener because of relationships in Strapi?

In part, yes. I am building a search engine for laptops and have created relations and components inside Strapi for everything that could be a facet or a filter (CPU, RAM, graphics card, storage, dimensions, etc). But most of those are sent as objects so they are of no use to me.

**Comment by bidoubiwa** [comment]
> Ok, I had thought about adding it to this plugin as a checkbox in the plugin's admin route. I'm just thinking of using flattie. Any recommendation on how to start? Should I directly do it on top of meilisearch-js, this plugin or MS itself?

Ah sorry, I did not understand that. I miss read your proposition. I'm not sure about the usage of your flatener .`"field1:field2":string, "field1:field3":string.`. How would you use it with MeiliSearch?


This is what I will be adding in the future to the plugin:

1. Check the collection you want to add to MeiliSearch
2. If there are relations, ask the user for each relation which field should be used

Example: 
1. Add restaurants
2. A relation is found with Category
3. `Which field will be showcased?`: Chose name field

Restaurants will be added the following way to MeiliSearch (I have removed all the created* and updated* in #77)
```
{
   "id": 1,
   "name": "nice snack",
   "description": "...",
   "category": ["snack", "fast-food"]
}
``` 

Then, once you have added `category` to the [attributes for faceting](https://docs.meilisearch.com/reference/api/attributes_for_faceting.html#attributes-for-faceting)

you would be able to do front-end searches like this:
```javascript
client.index('restaurant')
  .search('nice', {
    facetFilters: [['category:snack', 'category:fast-food']]
  })
```

Is this something that would help your use case?

**Comment by LtdJorge** [comment]
It would, but in my case, I need more than one facet attribute per relation (or object).
Here's a cleaned example retrieved from Strapi: 
```json
{
        "id": 3,
        "name": "ROG Zephyrus G15 2021",
        "model": "GA503QM-HQ120R",
        "cpu": {
            "id": 3,
            "name": "5900HS",
            "fullName": "AMD Ryzen 9 5900HS",
            "dateAdded": "2021-03-20",
            "published_at": "2021-03-20T16:06:26.000Z",
            "cpu_brand": 1,
            "cores": 8,
            "smt": 2,
            "pcie": "5",
            "tdp": 35,
            "baseFrequency": 3000,
            "maxFrequency": 4600,
            "cpu_codename": 2,
            "cpu_generation": 4,
            "cpu_lithography": 5,
            "replaceable": false,
            "l3Cache": 16000,
            "releaseDate": null,
            "gpu": 2,
            "L1Cache": 512,
            "L2Cache": 4096
        },
}
```
I just left some base attributes plus one relation, the CPU. In this case I would use the CPU name as a facet, but I also need other CPU attributes to be filters/facets, maybe the user doesn't know the name of the CPU, but knows the number of cores they need.

The flattening process would leave it as:
```json
{
        "id": 3,
        "name": "ROG Zephyrus G15 2021",
        "model": "GA503QM-HQ120R",
        "cpu:id": 3,
        "cpu:name": "5900HS",
        "cpu:fullName": "AMD Ryzen 9 5900HS",
        "cpu:dateAdded": "2021-03-20",
        "cpu:published_at": "2021-03-20T16:06:26.000Z",
        "cpu:cpu_brand": 1,
        "cpu:cores": 8,
        "cpu:smt": 2,
        "cpu:pcie": "5",
        "cpu:tdp": 35,
        "cpu:baseFrequency": 3000,
        "cpu:maxFrequency": 4600,
        "cpu:cpu_codename": 2,
        "cpu:cpu_generation": 4,
        "cpu:cpu_lithography": 5,
        "cpu:replaceable": false,
        "cpu:l3Cache": 16000,
        "cpu:releaseDate": null,
        "cpu:gpu": 2,
        "cpu:L1Cache": 512,
        "cpu:L2Cache": 4096
}
```

**Comment by LtdJorge** [comment]
The use of `:` as a glue is just an example that only adds one distance to the proximity rule.

**Pull request merged**
