### PR TITLE
Next v0.4.0 release

### PR DESCRIPTION
**Pull request by bidoubiwa**
## Important

- Only works with the newest v0.24.0 version of MeiliSearch
- Introduces a new way to index your data in MeiliSearch. You will need to re-index your content ⚠️

## Important

- ⚠️ Introduces a new way to index your data in MeiliSearch. You will need to re-index your content ⚠️
- Only works with the newest v0.24.0 version of MeiliSearch

## Features

- [Custom configuration file](./custom-configuration)
- [Custom index name](./custom-index-name)
- [Multiple collections in one index](./multiple-collections-in-the-same-index)
- [Transform entries before indexation](./transform-sent-data)
- [Permission system](./better-permission-system)
- [Error notification on failed entries indexation](./error-notification-on-failed-entries-indexation)

## Small changes
- [Checkbox to index instead of row](./use-checkbox-to-add-collection-instead-of-row)
- [Clarity on different api keys](./use-checkbox-to-add-collection-instead-of-row)

### Custom Configuration

Inside the `api/[collection]/model` folder of all existing collections, there is an associated `[collection_name].js` file. In this condiguration file it is now possible to add information about how your collection should act with MeiliSearch.

All possible configurations are explained in the next sections.

**Example**
```js
// api/restaurant/models/restaurant.js

module.exports = {
  meilisearch: {
    // parameters
  }
}
```

### Custom Index Name

Previously, when adding a collection to MeiliSearch you had no choice on the index naming, it was the same as the collection name.

For example, when adding the `restaurant` collection to MeiliSearch, the `indexUid` inside MeiliSearch would also be called `restaurant`.

With this new version, it is now possible to define a custom index name in your collections model options.

```js
// api/restaurant/models/restaurant.js

module.exports = {
  meilisearch: {
    indexName: "my_restaurants"
  }
}
```

### Multiple collections in the same index

You can point multiple collections to the same index.
For example if you want both entries from `shoes` and `shirts` to go to the same index, they need to share the same `indexName`, for example `clothes`.

```js
// api/shoes/models/shoes.js

module.exports = {
  meilisearch: {
    indexName: "clothes"
  }
}
```

```js
// api/shirts/models/shirts.js

module.exports = {
  meilisearch: {
    indexName: "clothes"
  }
}
```

### Transform sent data

Before, the whole entry of a collection was sent to MeiliSearch. Including all the sensitive fields about the authors for example. There was no way to decide which field to send to MeiliSearch.

It is now possible by setting a `transformEntry` function in the configuration file of the collection's model ([lots of examples here](./resources/entries-transformers))

Example to sanitize your field, and thus removing all sensitive data:

```js
// api/restaurant/models/restaurant.js
const { sanitizeEntity } = require('strapi-utils')

module.exports = {
  meilisearch: {
    transformEntry({ entry, model }) {
      return sanitizeEntity(entry, { model })
    },
  },
}
```

For example, you can now:
- Remove specific rows,
- Sanitize the content of private fields
- Change the content of a field

⚠️ Avoid playing around with the `id` fields as it is possible your collections may be duplicated in an index.

### Error notification on failed entries indexation

When indexing a collection by clicking on the un-checked you receive a notification when the index has been created successfully in MeiliSearch.
Nonetheless, if the entries addition fails, you receive no explanation as to why. The only information you see is that the counter stays at `0`.

This release tracks the entries addition process and raises error notifications as to why documents were not able to be added.

### Better permission system

Since `strapi-plugin-users-permissions` is not a mandatory plugin, the new permission system is very basic. Now, You need to be an `admin` in the admin panel to access or use any of the API routes of the MeiliSearch plugin.

### Use the checkbox to add collection instead of row

Previously, when clicking on the row of a collection, indexation or removal was triggered. This was non-intuitive and has been removed. Now to add or remove a collection from MeiliSearch you need to click on the checkbox

### Clarity on different API keys

It was not clear that the plugin required either the master key or the private key to be able to use the plugin. This leads to users using the same key in their front end to make search requests.

You need to use the `public` key in your front-end app and the `private` or `master-key` in Strapi. [See keys documentation](https://docs.meilisearch.com/reference/features/authentication.html#authentication)

fixes: #42
fixes: #112
fixes: #193
fixes: #218
fixes: #249
fixes: #284
fixes: #279
fixes: #191
fixes: #117 
fixes: #126 

## TODO 
- [x] #126
- [x] #117 
- [x] #191
- [x] #279
- [x] #284
- [x] #42
- [x] #112
- [x] #193
- [x] #218
- [x] #249
- [x] #270

### CODE REVIEW

**Comment by haye-webbio** [comment]
When are you planning on releasing this PR?

**Comment by bidoubiwa** [comment]
@haye-webbio Today or tomorrow. I think today but just in case it might be tomorrow

**Comment by haye-webbio** [comment]
> @haye-webbio Today or tomorrow. I think today but just in case it might be tomorrow

Looking forward to it! Thanks :)

**Comment by bidoubiwa** [comment]
bors merge

**Comment by bidoubiwa** [comment]
bors -r

**Review by alallema — APPROVED** [review]

**Review by alallema — APPROVED** [review]
LGTM! 🌮

**Comment by bidoubiwa** [comment]
bors merge

**Pull request merged**
